version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
    - checkout
    - run:
        name: Requirements
        command: |
          apk add ffmpeg aria2
    - run:
        name: Downloading
        command: |
         aria2c --check-certificate=false --min-split-size=100M --max-concurrent-downloads=16 --max-connection-per-server=16 --header 'Host: fr12.seedr.cc' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' --header 'Accept-Language: id,en-US;q=0.7,en;q=0.3' --referer 'https://www.seedr.cc/files/158892558' --header 'Upgrade-Insecure-Requests: 1' 'https://fr12.seedr.cc/ff_get/841552709/Mr.Queen.S01E16.1080p.WEB-DL.H264.AAC-AppleTor.mp4?st=gr0ko5GD95qwbRmjcJdkDg&e=1612387042' --out 'Mr.Queen.S01E16.1080p.WEB-DL.H264.AAC-AppleTor.mp4'
    - run:
        name: Rendering
        command: |
          ulimit -c unlimited
          ffmpeg -i "Mr.Queen.S01E16.1080p.WEB-DL.H264.AAC-AppleTor.mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="Mr. Queen Episode 16" -preset veryfast Mr.Queen.S01E16.1080p.WEB-DL.x265.mkv
          ls -hal
    - store_artifacts:
        path: Mr.Queen.S01E16.1080p.WEB-DL.x265.mkv
workflows:
  version: 2
  workflow:
    jobs:
    - build
