version: 2
# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: docker.pkg.github.com/5u9/test/ubuntu:20.04
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD  # context / project UI env-var reference
    steps:
    - checkout
    - run:
        name: Requirements
        command: |
          apt-get update && apt-get dist-upgrade -yqq && apt-get install -yqq sudo lsb-release apt-transport-https ca-certificates software-properties-common wget curl netcat aria2 whois figlet git p7zip p7zip-full zip unzip
          apt-get install -yqq wget aria2 httpie ffmpeg speedtest-cli telnet lshw tree
    - run:
        name: Downloading
        command: |
         aria2c --check-certificate=false --min-split-size=100M --max-concurrent-downloads=16 --max-connection-per-server=16 --header 'Host: fr8.seedr.cc' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' --header 'Accept-Language: id,en-US;q=0.7,en;q=0.3' --referer 'https://www.seedr.cc/files/153950765' --header 'Upgrade-Insecure-Requests: 1' 'https://fr8.seedr.cc/ff_get/810602626/The.Royal.Tailor.2014.720p.WEBRip.x264.AAC-[YTS.MX].mp4?st=CCFkfDOR3cQmVoYJ6YTB_w&e=1608834953' --out 'The.Royal.Tailor.2014.720p.WEBRip.x264.AAC-[YTS.MX].mp4'
    - run:
        name: Rendering
        command: |
          ulimit -c unlimited
          ffmpeg -i "The.Royal.Tailor.2014.720p.WEBRip.x264.AAC-[YTS.MX].mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="The Royal Tailor 2014" -preset veryfast The.Royal.Tailor.2014.720p.WEBRip.x265.mp4
          ls -hal
    - store_artifacts:
        path: The.Royal.Tailor.2014.720p.WEBRip.x265.mp4
workflows:
  version: 2
  workflow:
    jobs:
    - build
