version: 2
# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: docker.pkg.github.com/5u9/test/ubuntu:16.04
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD  # context / project UI env-var reference
    steps:
    - checkout
    - run:
        name: Requirements
        command: |
          apt-get update && apt-get dist-upgrade -yqq && apt-get install -yqq sudo lsb-release apt-transport-https ca-certificates software-properties-common wget curl netcat aria2 whois figlet git p7zip p7zip-full zip unzip
          apt-get install -yqq wget aria2 ffmpeg telnet lshw tree
    - run:
        name: Downloading
        command: |
         aria2c --check-certificate=false --min-split-size=100M --max-concurrent-downloads=16 --max-connection-per-server=16 https://www.dropbox.com/s/dl/cvs0zmcdqjka6pg/Awaken.E13.210111.720p-NEXT.mp4
    - run:
        name: Rendering
        command: |
          ulimit -c unlimited
          ffmpeg -i "Awaken.E13.210111.720p-NEXT.mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="Awaken Episode 13" -preset veryfast 13.mkv
          ls -hal
    - store_artifacts:
        path: 13.mkv
workflows:
  version: 2
  workflow:
    jobs:
    - build
